[firebase_service_account]
type = "service_account"
project_id = "peds-clerkship-doc"
private_key_id = "549892a28b467b6d620ae2e6db7588fc790fe730"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC/t7EXsDuscsC0
y6nlG1yPppHnT2dw+Ghl1tzviZdKVeHRDRqrK5zakFuHVdJIhUOiVPKw2HQZ2W6z
nCqk2/EnQFgnUERxd7/YWs6huMsV57O0L4bHgEHas23A4zNE/oXeVeakcLazaUPp
GF26OZI2g1P635TGySmrv5Lt0Y76BGV2Qmf3qzpzNh7mDVs/BHstndojekSGYoRo
69hyG1Lx8M7+rlXPe3qucMIv9ggLoyGDsBMlOetxBy1j5EZSOPIHLlwKuTrLz3qz
hPmlAQuF/Rp7umm7r3y+FeGNds16v1DLFMWg52lriJz/CzEzlTnZVkCnVJdqovVt
DNqlkp+9AgMBAAECggEABTVQtehvVpOV5KBIl0hgNVujFXoBjcu4M+9B+HsjOKPC
PlM+AqE54gr16zFLqyiwc69Qs7k0CwruVPbMucaeQIcg940/FSemdvkDwz6P7281
Li0njjGC/uJmlhmvm0cG2ZY5bWvNqtLhqdCkCzRKyPkixbf5N+ustCInAOSM686f
e47bQe6SRonnWBGxkVQpqyxu5ebvuqlYXMBwjavP1ivagl7wbHsNdHRDTFfAl25T
TbhN0aSKYRcec1/6KwEbw3V/vTf0PAWzXu25dYW4GgGyNd2DpnauKE8YDQIE1INr
rh2Gx2/g66kuc1NKf7g/QYIy+FiA1DKoiL/xd1HYwQKBgQDyTwocQiPqQfk82zD8
HveSWzU++xx6v/Rcqje0ih2PG77EFfNwC/TmzzwrsLxujsDfix+97bPU8AHyV5Gn
bZsL/y4ztCNjfsEIlsfiw0Y0sdcd333rjizd5f80e1RYwhkHqMzumnGK1eoyLGdv
L3jFDJP+IO0j1IOfgn67s3YmCQKBgQDKjNui9hXOVgWR/DfCBPEopOZEND0AAyB6
Q+iUN6ee21vfkWLmbB7UXByGTj5aoEvdbYxuPl+43WeIVcP9xFb8qwwQQFBE0DNJ
A3JvvGfXYsHvyjsCd0ExpzF74Xd8lPQ/mHkspE1xQb8+D4cj/dmKde6JBI2WdG9K
nQN6cX25FQKBgGrK0xXpQJL6SLK9mDVGIK7sa+c6HS8scrJ0guCbDrQH8mfRlN0J
KAKhy08mMaY4XGEpm+/FV8C9lt4MIjG8aN08tkwrVH2BW+pBKg+TKNoIl1qfKYwr
uTKDL5sdz+regNGTX965Stl5tiIu19d1ALE3/fG+6UUlYG1owhpP2f6hAoGAVMab
7xsciV4Lusxb8gLrhN1v20AZ//VPFJ1zrQWWTLD3RR2uzU6XoL5k2fnJs1jAKA9/
5WyJ1/AjMzbib0ZMOjjFNdAVSJfzvy2IKigrNkUJcvmrtR6A1O1rkrQNtMELccq5
fOvP1gV0q98H6xKGiKNPkV2sfTqCkjIhkJAL1PkCgYA3nvc7hEFlYnkVMaO0ANzU
VoJCmkI8myAtoApeJnE8DMGffHCH9dlnl//vdFJ4VlO/CYsn1woR3GNGC8RijGU+
de+OI57+rwfEJxUyxS+bIwB4DUZyWfvF2ljQR1HZic22u+YwwtZKNl0HC2bYurmI
B56g0xRwSeYfwkh50vt6jA==-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@peds-clerkship-doc.iam.gserviceaccount.com"
client_id = "107914882870603638435"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@peds-clerkship-doc.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
